export const GET_POKEMONS_REQUEST = "GET_POKEMONS_REQUEST";
export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_POKEMONS_ERROR = "GET_POKEMONS_ERROR";

export const GET_POKEMON_REQUEST = "GET_POKEMON_REQUEST";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_ERROR = "GET_POKEMON_ERROR";
