export const ACTION_POKEMONS_REQUEST = "ACTION_POKEMONS_REQUEST";
export const ACTION_POKEMONS_ERROR = "ACTION_POKEMONS_ERROR";

export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";

export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";

export const ADD_MY_POKEMON_SUCCESS = "ADD_MY_POKEMON_SUCCESS";

export const EDIT_MY_POKEMON_SUCCESS = "EDIT_MY_POKEMON_SUCCESS";

export const DELETE_MY_POKEMON_SUCCESS = "DELETE_MY_POKEMON_SUCCESS";
